version: '3'

services:
  influxdb:
    image: influxdb:2.6-alpine
    env_file:
      - influxv2.env
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influxdb:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"

  telegraf:
    image: telegraf:1.25-alpine
    depends_on:
      - influxdb
      - mosquitto
    volumes:
      # Mount for telegraf config
      - ./telegraf/mqtt.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - influxv2.env

  mosquitto:
      image: eclipse-mosquitto:2
      ports:
          - 2883:2883
          - 8883:8883
          - 9001:9001
      volumes:
          - ./mosquitto/config:/mosquitto/config
          - ./mosquitto/data:/mosquitto/data
